import {Dimensions} from 'react-native';
import {StyleSheet} from 'react-native';
import FONTS from '../../../utils/fonts';
import COLORS from '../../../utils/colors';

const {width} = Dimensions.get('screen');

const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 20,
  },
  heading: {
    fontSize: 28,
    lineHeight: 40,
    letterSpacing: 1,
    fontWeight: '900',
    fontStyle: 'italic',
    color: COLORS.WHITE,
  },

  headerView: {
    marginTop: 10,
    paddingHorizontal: 20,
    backgroundColor: COLORS.BLACK,
  },
  icon: {
    right: 20,
    width: 20,
    height: 20,
    bottom: 45,
    alignSelf: 'flex-end',
    resizeMode: 'contain',
  },
  rightArrow: {
    top: 18,
    right: 15,
    width: 20,
    height: 20,
    position: 'absolute',
    resizeMode: 'contain',
  },
  coverImgBg: {
    height: 180,
    width: '100%',
    borderWidth: 2,
    borderRadius: 5,
    borderColor: COLORS.GREY,
    backgroundColor: COLORS.DARKER_GREY,
  },
  profileImgBg: {
    top: 165,
    left: 43,
    width: 88,
    height: 88,
    borderWidth: 2,
    borderRadius: 5,
    position: 'absolute',
    borderColor: COLORS.GREY,
    backgroundColor: COLORS.DARKER_GREY,
  },
  coverImg: {
    height: 180,
    width: '100%',
    borderWidth: 2,
    borderRadius: 5,
    borderColor: COLORS.WHITE,
  },
  profileImg: {
    top: 165,
    left: 43,
    width: 88,
    height: 88,
    borderWidth: 2,
    borderRadius: 5,
    position: 'absolute',
    borderColor: COLORS.WHITE,
  },
  cover: {
    width: '100%',
    height: 180,
    marginTop: 32,
    marginBottom: 64,
  },
  profile: {
    width: 88,
    height: 88,
    position: 'absolute',
  },
  camera: {
    top: 80,
    zIndex: 1,
    width: 20,
    height: 20,
    opacity: 0.6,
    alignSelf: 'center',
    position: 'absolute',
    resizeMode: 'contain',
  },
  cameraProfile: {
    top: 200,
    left: 78,
  },
  input: {
    marginVertical: 7,
    width: width * 0.89,
    justifyContent: 'center',
  },
  text: {
    fontSize: 16,
    marginLeft: 16,
    fontWeight: '600',
    color: COLORS.WHITE,
    fontFamily: FONTS.HELVETICA,
  },
  emptyComponent: {
    left: 8,
    width: 60,
    height: 20,
    bottom: 28,
    resizeMode: 'contain',
    alignSelf: 'flex-end',
  },
  charLength: {
    fontSize: 12,
    color: COLORS.GREY,
  },
  tile: {
    height: 30,
    margin: 10,
    borderRadius: 5,
    paddingVertical: 6,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    justifyContent: 'center',
    backgroundColor: COLORS.DARK_GREY,
  },
  tileText: {
    fontSize: 12,
    fontWeight: '900',
    color: COLORS.WHITE,
  },
  sportsList: {
    padding: 10,
    borderWidth: 2,
    borderRadius: 5,
    flexWrap: 'wrap',
    marginVertical: 10,
    width: width * 0.89,
    paddingVertical: 16,
    flexDirection: 'row',
    borderColor: COLORS.WHITE,
  },
  identityView: {
    height: 60,
    padding: 10,
    borderWidth: 2,
    borderRadius: 5,
    marginBottom: 26,
    marginVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    width: width * 0.89,
    borderColor: COLORS.WHITE,
    justifyContent: 'space-between',
  },
  sportsListText: {
    fontSize: 16,
    fontWeight: '600',
    width: width * 0.79,
    color: COLORS.WHITE,
    backgroundColor: COLORS.BLACK,
  },
  addMore: {
    fontSize: 14,
    fontWeight: '900',
    fontStyle: 'italic',
    alignSelf: 'center',
    color: COLORS.BLUE,
  },
  fixedLabel: {
    top: -12,
    left: 10,
    fontSize: 12,
    paddingVertical: 4,
    position: 'absolute',
    color: COLORS.WHITE,
    paddingHorizontal: 6,
    backgroundColor: COLORS.BLACK,
  },
  usernameSuggestionText: {
    fontSize: 15,
    letterSpacing: 0.6,
    color: COLORS.WHITE,
    fontFamily: FONTS.HELVETICA,
  },
  errText: {
    top: -18,
    fontSize: 12,
    color: COLORS.RED,
    fontFamily: FONTS.HELVETICA,
  },
  usernameSuggestionView: {
    top: -6,
    flexDirection: 'row',
  },
});

export default styles;
