export const Details = [
    {
      dp: require('../assets/DP/1.webp'),
      username: 'dattebayo',
      likes: '1,345,334',
      caption: 'Saaaaaasukkkkkeeeeeee 😡😡😡!!!!',
      post: require('../assets/posts/1.webp'),
      comments: '25,316',
      time: '2 hours ago',
      followers: '1.5M',
      following: '50',
      posts: '34',
      bio: 'Naruto Uzumaki',
      sampleBio: 'THis is sample bio....',
      linkInBio: 'www.github.com/4shu10sh',
      reel: 'https://assets.mixkit.co/videos/preview/mixkit-man-dancing-under-changing-lights-1240-large.mp4',
    },
    {
      dp: require('../assets/DP/2.jpeg'),
      username: 'godhimself',
      likes: '32,453,543',
      caption: 'I have met God -- He is me. 😎💪🔥',
      post: require('../assets/posts/2.webp'),
      comments: '65,417',
      time: '2 hours ago',
      followers: '9.8M',
      following: '26',
      posts: '98',
      bio: 'Son Goku',
      sampleBio: 'THis is sample bio....',
      linkInBio: 'www.github.com/4shu10sh',
      reel: 'https://assets.mixkit.co/videos/preview/mixkit-winter-fashion-cold-looking-woman-concept-video-39874-large.mp4',
    },
    {
      dp: require('../assets/DP/3.png'),
      username: 'detectiveofthecentury',
      likes: '13,342,432',
      caption: 'Sherlock who? 🤔',
      post: require('../assets/posts/3.webp'),
      comments: '95,319',
      time: '3 hours ago',
      followers: '20M',
      following: '1',
      posts: '1,987',
      bio: 'L',
      sampleBio: 'THis is sample bio....',
      linkInBio: 'www.github.com/4shu10sh',
      reel: 'https://assets.mixkit.co/videos/preview/mixkit-tree-with-yellow-flowers-1173-large.mp4',
    },
    {
      dp: require('../assets/DP/4.jpeg'),
      username: 'pirateking',
      likes: '34,923,232',
      caption: "Where's my treasure? 🤩💰",
      post: require('../assets/posts/4.webp'),
      comments: '15,210',
      time: '3 hours ago',
      followers: '50M',
      following: '32',
      posts: '121',
      bio: 'Monkey D. Luffy ',
      sampleBio: 'Hello, this is sample bio....',
      linkInBio: 'www.github.com/4shu10sh',
      reel: 'https://assets.mixkit.co/videos/preview/mixkit-pink-and-blue-ink-1192-large.mp4',
    },
    {
      dp: require('../assets/DP/5.jpeg'),
      username: 'moonchild',
      likes: '428,342,987',
      caption: 'I looked so cute as a kid 😊😊😊',
      post: require('../assets/posts/5.webp'),
      comments: '10,916',
      time: '4 hours ago',
      followers: '63M',
      following: '234',
      posts: '199',
      bio: 'Princess Kaguya',
      sampleBio: 'Hello, this is sample bio....',
      linkInBio: 'www.github.com/4shu10sh',
      reel: 'https://assets.mixkit.co/videos/preview/mixkit-mother-with-her-little-daughter-eating-a-marshmallow-in-nature-39764-large.mp4',
    },
    {
      dp: require('../assets/DP/6.jpeg'),
      username: 'kiki',
      likes: '12,986,353',
      caption: 'Contemplating about life...😌🌻',
      post: require('../assets/posts/6.jpeg'),
      comments: '65,656',
      time: '4 hours ago',
      followers: '3.3M',
      following: '89',
      posts: '65',
      bio: "Kiki's Delivery Serivice",
      sampleBio: 'Hello, this is sample bio....',
      linkInBio: 'www.github.com/4shu10sh',
      reel: 'https://assets.mixkit.co/videos/preview/mixkit-red-frog-on-a-log-1487-large.mp4',
    },
    {
      dp: require('../assets/DP/7.webp'),
      username: 'saitama',
      likes: '999,999,999,999,999',
      caption: "When's the next sale coming? 😬",
      post: require('../assets/posts/7.webp'),
      comments: '88,316',
      time: '5 hours ago',
      followers: '999M',
      following: '0',
      posts: '99',
      bio: 'One Punch Man',
      sampleBio: 'Hello, this is sample bio....',
      linkInBio: 'www.github.com/4shu10sh',
      reel: 'https://assets.mixkit.co/videos/preview/mixkit-photo-session-of-a-girl-in-the-desert-34405-large.mp4',
    },
    {
      dp: require('../assets/DP/8.jpeg'),
      username: 'dogoodbegood',
      likes: '98,768,004',
      caption: 'I met Emi today heuheuheu ❤️❤️❤️',
      post: require('../assets/posts/8.webp'),
      comments: '25,316',
      time: '5 hours ago',
      followers: '1.5M',
      following: '50',
      posts: '34',
      bio: 'Mob',
      sampleBio: 'Hello, this is sample bio....',
      linkInBio: 'www.github.com/4shu10sh',
      reel: 'https://assets.mixkit.co/videos/preview/mixkit-man-runs-past-ground-level-shot-32809-large.mp4',
    },
    {
      dp: require('../assets/DP/9.webp'),
      username: 'spiritedaway',
      likes: '723,644,398',
      caption: 'Not all spirits 💀 are scary! 😁',
      post: require('../assets/posts/9.jpeg'),
      comments: '98,123',
      time: '6 hours ago',
      followers: '1.5M',
      following: '50',
      posts: '34',
      bio: 'Chihiro Ogino',
      sampleBio: 'Hello, this is sample bio....',
      linkInBio: 'www.github.com/4shu10sh',
      reel: 'https://assets.mixkit.co/videos/preview/mixkit-silhouette-of-urban-dancer-in-smoke-33898-large.mp4',
    },
    {
      dp: require('../assets/DP/10.jpeg'),
      username: 'jiro',
      likes: '34,786,321',
      caption: 'Good day today.✨',
      post: require('../assets/posts/10.jpeg'),
      comments: '11,311',
      time: '6 hours ago',
      followers: '9.8M',
      following: '26',
      posts: '98',
      bio: 'The Wind Rises',
      sampleBio: 'Hello, this is sample bio....',
      linkInBio: 'www.github.com/4shu10sh',
      reel: 'https://assets.mixkit.co/videos/preview/mixkit-little-girl-opening-christmas-gifts-with-her-parents-39751-large.mp4',
    },
  ];
  