const LOCAL_IMAGES = {
    OPEN_EYE: require('../assets/images/OpenEye.png'),
    CLOSED_EYE: require('../assets/images/ClosedEye.png'),
    FIVE_LOGO: require('../assets/images/FiveLogo.png'),
    APPLE_BUTTON: require('../assets/images/AppleButton.png'),
    STAR: require('../assets/images/Star.png'),
    BACK_BUTTON: require('../assets/images/BackButton.png'),
    BMX1: require('../assets/images/Bmx1.png'),
    BORDER: require('../assets/images/Border.png'),
    GOOGLE_BUTTON: require('../assets/images/GoogleButton.png'),
    LIKE: require('../assets/images/Like.png'),
    MODAL_RECTANGLE: require('../assets/images/ModalRect.png'),
    SPLASH_SCREEN: require('../assets/images/SplashScreen.png'),
    TIMER: require('../assets/images/Timer.png'),
    FAN_BANNER: require('../assets/images/FanBanner.png'),
    ATHLETE_BANNER: require('../assets/images/AthleteBanner.png'),
    CHECK: require('../assets/images/Check.png'),
    PENCIL: require('../assets/images/Pencil.png'),
    CAMERA: require('../assets/images/Camera.png'),
    RIGHT_ARROW: require('../assets/images/RightArrow.png'),
    CALENDAR: require('../assets/images/Calendar.png'),
    CROSS: require('../assets/images/Cross.png'),
    SELECTED: require('../assets/images/Selected.png'),
    SEARCH_ICON: require('../assets/images/SearchIcon.png'),
    NO_DATA: require('../assets/images/NoData.png'),
    EMPTY_BOX: require('../assets/images/EmptyBox.png'),
    CLOSE_BUTTON: require('../assets/images/CloseButton.png'),
}

export default LOCAL_IMAGES;