const STRINGS = {
  COMMON: {
    SEARCH: 'Search',
    NEW_USER: "I'm a new user ",
    NO_DATA_FOUND: 'No Result Found',
    CREATE_ACCOUNT: 'Create Account',
    SEARCH_ATHLETE: 'Search Athletes',
    SEARCH_ZIP_CODE: 'Search Zip Code',
    CONGRATULATIONS: 'Congratulations',
    WHO_ARE_YOU_HEADING: 'Who are you?',
    FORGOT_PASSWORD: 'Forgot Password?',
    CANNOT_FETCH_DATA: 'Cannot fetch data',
    RESEND_CODE: 'Resend Verification Code',
    ALREADY_HAVE_ACCOUNT: 'Already a user? ',
    SIGN_UP_HEADING: 'Signup to get started',
    GREETING_HEADING: 'Tell us about yourself',
    VERIFY_OTP_HEADING: 'Enter Verification Code',
    DIDNT_RECEIVE_CODE: "Didn't receive the code yet? ",
    CANNOT_FETCH_DATA_DESC: 'Sorry, something went wrong!',
    SELECT_SPORTS_HEADING: 'Which sports do you like to watch?',
    SIGN_IN_HEADING: 'Sign In Using Your Mobile Number / Email',
    ENTER_CODE: 'Kindly enter the 4 digit verification code sent to',
    YOU_ARE_REGISTERED: 'Your account has been successfully registered',
    ATHLETE_RECOMMENDATION_HEADING: 'Some of the most followed Athletes',
    NO_DATA_FOUND_DESC: 'Sorry, no search results found for your search ',
  },
  LABEL: {
    BIO: 'Bio',
    FAN: 'Fan',
    NEXT: 'Next',
    EMAIL: 'Email',
    FOLLOW: 'Follow',
    SUBMIT: 'Submit',
    ZIPCODE: 'Zipcode',
    SIGN_IN: 'Sign In',
    ATHLETE: 'Athlete',
    SIGN_UP: 'Sign Up',
    CONTINUE: 'Continue',
    USERNAME: 'Username',
    PASSWORD: 'Password',
    FULL_NAME: 'Full Name',
    ADD_MORE: '+ Add More',
    FOLLOWING: 'Following',
    DOB: 'DOB (MM/DD/YYYY)',
    SPORTS_WATCH: 'Sports|Watch',
    COUNTRY_CODE: 'Country Code',
    PHONE_NUMBER: 'Mobile Number',
    REFERAL_CODE: 'Referral Code',
    CHANGE_USERNAME: 'Change your Username',
    SELECT_IDENTITY: 'Select your Identity',
  },

  ERROR_MSG: {
    NAME_REQUIRED: 'Name is required',
    EMAIL_REQUIRED: 'Email is required',
    PASSWORD_REQUIRED: 'Password is required',
    ENTER_VALID_OTP: 'Please enter a valid OTP',
    ENTER_VALID_EMAIL: 'Please enter a valid email',
    PHONE_NUMBER_REQUIRED: 'Phone Number is required',
    COUNTRY_CODE_REQUIRED: 'Country Code is required',
    ENTER_VALID_PASSWORD: 'Please enter a valid password',
    ENTER_VALID_NAME: 'Name should be min of 3 characters',
    ENTER_VALID_PHONE_NUMBER: 'Mobile number must contain 10 digits',
  },
  ACTION_TYPE: {
    SIGN_IN: 'SIGN_IN',
    SIGN_UP: 'SIGN_UP',
    VERIFY_OTP: 'VERIFY_OTP',
    SPORTS_WATCH: 'SPORTS_WATCH',
    RESET_PASSWORD: 'RESET_PASSWORD',
    FORGOT_PASSWORD: 'FORGOT_PASSWORD',
    VERIFICATION_SUCCESS: 'VERIFICATION_SUCCESS',
  },
};

export default STRINGS;
